# Data
path: ../data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [19, 3]  # [number of keypoints, number of dim]

flip_idx: [7,6,5, 3,4,  2,1,0,  8,9,11,10,   12,   16,17,18, 13,14,15]
#flip_idx: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]

# Classes
names:
  0: player